### ISSUE TITLE
执行了你的脚步，把我之前的配置全删除掉，真得合适吗？

### ISSUE THREAD

**Issue by taodream518** [shenmishajing/Setting-for-Mac#2]

**Comment by shenmishajing** [comment]
emmmm……这是我自己用的配置文件，方便搭新环境的，写的时候没考虑过其他人用的情况……所以直接rm而不是mv是为了方便我不用自己再手动rm一遍……

你想用的话，可以自己fork一份，然后把自己的配置都commit起来，就不会丢了

**Comment by shenmishajing** [comment]
而且README里也写了跑之前先看看脚本内容是不是你想要的……

**Comment by taodream518** [comment]
没看脚步内容，跑完后结果发现配置全没了呜呜～。后续又花时间配置了一份
